repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.4
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
      exclude: ^(docs/|tests)
    - id: ruff-format

- repo: https://github.com/codespell-project/codespell
  rev: v2.3.0
  hooks:
  - id: codespell
    additional_dependencies: ["tomli"]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-merge-conflict
  - id: debug-statements
  - id: trailing-whitespace

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.11.0
  hooks:
  - id: mypy
    exclude: ^(docs/|tests)
    additional_dependencies: [
    "sqlalchemy",
    "toml==0.10.2",
  ]

- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v4.0.0-alpha.8
  hooks:
    - id: prettier
      name: Prettier (TypeScript)
      files: \.ts$|\.tsx$

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.29.0
  hooks:
    - id: check-github-workflows
