version: '3.8'

services:
  webapp:
    build: .
    ports:
      - "8000:8000"
    command: uvicorn pyvista_webapp.main:app --host 0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 10s